server:
  port: 8081

spring:
  application:
    name: study-project-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.240.179:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: codeLamb@163.com
    password: AJGTCQQOXZGGJHZL
    default-encoding: utf-8
    properties:
      from: codeLamb@163.com

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

